Offwind.WebApp/Offwind.WebApp/Areas/EngineeringTools/Models/WakeSimulation2New/VGeneralProperties.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Offwind.WebApp.Models;

namespace Offwind.WebApp.Areas.EngineeringTools.Models.WakeSimulation2New
{
    public class VGeneralProperties : VWebPage
    {
        public string WindFarm { set; get; }
        //public double[,] Turbines { set; get; }

        [DisplayName("Enable Power Distribution?")]
        [Description("Enables wind farm control and not only constant power")]
        public bool EnablePowerDistribution { set; get; }
        [DisplayName("Enable Turbine Dynamics?")]
        [Description("Enable Dynamic Turbine Model")]
        public bool EnableTurbineDynamics { set; get; }
        [DisplayName("Enable Power Reference Interpolation")]
        [Description("Enable Power Reference Interpolation")]
        public bool PowerRefInterpolation { set; get; }
        [DisplayName("Enable a Varying Demand")]
        [Description("Enables a Power Demand that varies")]
        public bool EnableVaryingDemand { set; get; }

        [DisplayName("End Time")]
        [Description("end time of simulation")]
        [Range(0.1, 10800)]
        public decimal StopTime { set; get; }
        [DisplayName("Time Step")]
        [Description("time Step")]
        public decimal TimeStep { get { return 0.1m; } }
        [DisplayName("Update Interval, Control")]
        [Description("update time of controller")]
        public decimal ControlUpdateInterval { set; get; }
        [DisplayName("Update Interval, Power")]
        [Description("update time of the power reference")]
        public decimal PowerUpdateInterval { set; get; }
        [DisplayName("Initial Power Demand")]
        [Description("The initial Power demand, if the varying demand option is set to \"false\" this will remain constant throughout the simulation")]
        public decimal InitialPowerDemand { set; get; }

        public VGeneralProperties()
        {
            WindFarm = "";
            //Turbines = new double[0, 0];

            EnablePowerDistribution = true;
            EnableTurbineDynamics = true;
            PowerRefInterpolation = true;
            EnableVaryingDemand = true;

            StopTime = 100;
            //TimeStep = 0.125m;
            ControlUpdateInterval = 5;
            PowerUpdateInterval = 1;
            InitialPowerDemand = (decimal)(50 * 5e6);
        }
    }
}

Offwind.WebApp/Offwind.WebApp/Areas/EngineeringTools/Models/WakeSimulation2New/VNowcastingProperties.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Offwind.WebApp.Models;

namespace Offwind.WebApp.Areas.EngineeringTools.Models.WakeSimulation2New
{
    public enum NowcastingSimulationMethod
    {
        [Display(Name = "AR(1)")]
        a,
        [Display(Name = "Persistence")]
        p
    }

    public class VNowcastingProperties : VWebPage
    {
        //public bool WasWakeSimulationPerformed = false;

        public NowcastingSimulationMethod Method { set; get; }

        [DisplayName("Time for starting")]
        [Description("Time for starting multi step prediction. If < 1 it is assumed  a fraction of the end time")]
        public decimal TimeForStarting { set; get; }
        [DisplayName("Decimation")]
        [Description("Decimation with a moving average of order")]
        public int Decimation { set; get; }
        [DisplayName("Sampling time")]
        [Description("Sampling time")]
        public decimal SamplingTime { set; get; }

        public VNowcastingProperties()
        {
        }
    }
}

Offwind.WebApp/Offwind.WebApp/Areas/EngineeringTools/Controllers/WakeSimulation2NewController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using EmitMapper;
using Offwind.WebApp.Areas.EngineeringTools.Models.WakeSimulation2New;
using WakeFarmControl;
using WakeFarmControl.Input;


namespace Offwind.WebApp.Areas.EngineeringTools.Controllers
{
    public class WakeSimulation2NewController : _BaseController
    {
        const string SimulationPageTitle = "Input | Wake Simulation II-New | Offwind";
        const string ResultsPageTitle = "Results | Wake Simulation II-New | Offwind";
        const string NowcastingPageTitle = "Nowcasting | Wake Simulation II-New | Offwind";

        private VGeneralProperties _model
        {
            get
            {
                return (VGeneralProperties)(Session["WindFarmControlNew.GeneralProperties"]);
            }
            set
            {
                Session["WindFarmControlNew.GeneralProperties"] = value;
            }
        }

        private List<string> _wfl
        {
            get
            {
                var wfl = (List<string>)(Session["WindFarmControlNew.WindFarmsList"]);
                if (wfl == null)
                {
                    wfl = new List<string>();
                    Session["WindFarmControlNew.WindFarmsList"] = wfl;
                }
                return wfl;
            }
            set
            {
                Session["WindFarmControlNew.WindFarmsList"] = value;
            }
        }

        private List<decimal[]> _simulationTurbines
        {
            get
            {
                return (List<decimal[]>)(Session["WindFarmControlNew.SimulationTurbines"]);
            }
            set
            {
                Session["WindFarmControlNew.SimulationTurbines"] = value;
            }
        }

        private decimal _simulationTimeStep
        {
            get
            {
                return (decimal)(Session["WindFarmControlNew.SimulationTimeStep"] ?? ((decimal)0));
            }
            set
            {
                Session["WindFarmControlNew.SimulationTimeStep"] = value;
            }
        }

        private double[][] _simulation
        {
            get
            {
                return (double[][])(Session["WindFarmControlNew.Simulation"]);
            }
            set
            {
                Session["WindFarmControlNew.Simulation"] = value;
            }
        }

        private double[][] _simulationDataOut
        {
            get
            {
                return (double[][])(Session["WindFarmControlNew.SimulationDataOut"]);
            }
            set
            {
                Session["WindFarmControlNew.SimulationDataOut"] = value;
            }
        }

        private List<string> _simulationInformationMessages
        {
            get
            {
                return (List<string>)(Session["WindFarmControlNew.SimulationInformationMessages"]);
            }
            set
            {
                Session["WindFarmControlNew.SimulationInformationMessages"] = value;
            }
        }

        private VNowcastingProperties _nowcastingModel
        {
            get
            {
                return (VNowcastingProperties)(Session["WindFarmControlNew.NowcastingModel"]);
            }
            set
            {
                Session["WindFarmControlNew.NowcastingModel"] = value;
            }
        }

        private WakeFarmControl.NowCast.NowCastSimulationResult _nowcastingSimulationResult
        {
            get
            {
                return (WakeFarmControl.NowCast.NowCastSimulationResult)(Session["WindFarmControlNew.NowcastingSimulationResult"]);
            }
            set
            {
                Session["WindFarmControlNew.NowcastingSimulationResult"] = value;
            }
        }

        private List<string> _nowcastingSimulationWarningMessages
        {
            get
            {
                return (List<string>)(Session["WindFarmControlNew.NowcastingSimulationWarningMessages"]);
            }
            set
            {
                Session["WindFarmControlNew.NowcastingSimulationWarningMessages"] = value;
            }
        }

        public ActionResult Simulation()
        {
            ViewBag.Title = SimulationPageTitle;
            if (_model == null)
            {
                _model = new VGeneralProperties();
                //_model.TimeStep = (decimal)(0.1);
                //_wfl = new List<string>();
                _simulation = null;
                _simulationDataOut = null;
                _nowcastingSimulationResult = null;
                _nowcastingSimulationWarningMessages = null;
            }
            var model = new VGeneralProperties();
            ObjectMapperManager.DefaultInstance.GetMapper<VGeneralProperties, VGeneralProperties>().Map(_model, model);
            return View(model);
        }

        [HttpPost]
        public ActionResult Simulation(VGeneralProperties model)
        {
            if (_model == null)
            {
                return RedirectToAction("Simulation");
            }
            ViewBag.Title = SimulationPageTitle;
            lock (_model)
            {
                model.WindFarm = _model.WindFarm;
                ObjectMapperManager.DefaultInstance.GetMapper<VGeneralProperties, VGeneralProperties>().Map(model, _model);
            }
            var dWindFarm = _ctx.DWindFarms.First(e => _model.WindFarm == e.Name);
            var turbines = dWindFarm.DWindFarmTurbines.OrderBy(t => t.Number).Select(t => new decimal[] { t.Number, t.X, t.Y }).ToList();
            var turbinesCoordinates = new double[turbines.Count, 2];
            for (var index = 0; index < turbinesCoordinates.GetLength(0); index++)
            {
                var turbine = turbines[index];
                turbinesCoordinates[index, 0] = (double)(turbine[1]);
                turbinesCoordinates[index, 1] = (double)(turbine[2]);
            }

            var config = new WakeFarmControlR.WakeFarmControlConfig()
            {
                Turbines = turbinesCoordinates,
            };
            config.enablePowerDistribution = _model.EnablePowerDistribution;
            config.enableTurbineDynamics = _model.EnableTurbineDynamics;
            config.powerRefInterpolation = _model.PowerRefInterpolation;
            config.enableVaryingDemand = _model.EnableVaryingDemand;

            config.SimParm.timeStep = (double)_model.TimeStep;
            config.SimParm.tEnd = (double)_model.StopTime;
            config.SimParm.ctrlUpdate = (double)_model.ControlUpdateInterval;
            config.SimParm.powerUpdate = (double)_model.PowerUpdateInterval;
            config.InitialPowerDemand = (double)_model.InitialPowerDemand;

            config.NREL5MW_MatFile = WebConfigurationManager.AppSettings["WakeFarmControlRNREL5MW"]; // @"c:\farmcontrol\NREL5MW_Runc.mat";
            config.Wind_MatFile = WebConfigurationManager.AppSettings["WakeFarmControlRWind"]; // @"c:\farmcontrol\wind_Runc.mat";

            double[][] simulationDataOut;
            List<string> simulationInformationMessages;
            _simulation = WakeFarmControlR.FarmControl.Simulation(config, out simulationDataOut, out simulationInformationMessages);
            _simulationTurbines = turbines;
            _simulationTimeStep = _model.TimeStep;
            _simulationDataOut = simulationDataOut;
            _simulationInformationMessages = simulationInformationMessages;
            return RedirectToAction("Results");
        }

        public ActionResult Results()
        {
            ViewBag.Title = ResultsPageTitle;
            ViewBag.WasWakeSimulationPerformed = !(_simulationDataOut == null);
            //if (_simulation != null)
            //{
            //    var res = new {
            //                    informationMessages = _simulationInformationMessages,
            //                    data = _simulation.Select(x => new object[] { x }).ToArray()
            //    };
            //    return View(res);
            //}
            return View((object)null);
        }

        public ContentResult GetSimulationResults()
        {
            var serializer = new JavaScriptSerializer();

            // For simplicity just use Int32's max value.
            // You could always read the value from the config section mentioned above.
            serializer.MaxJsonLength = Int32.MaxValue;

            //var res = _simulation.Select(x => new object[] { x }).ToArray();
            var turbines = (_simulationTurbines ?? new List<decimal[]>()).Select(t => new { n = (int)(t[0]), x = t[1], y = t[2] }).ToArray();
            var res = new {
                            informationMessages = _simulationInformationMessages,
                            turbines = turbines,
                            data = (_simulation ?? new double[0][]).Select(x => new object[] { x }).ToArray()
            };
            var result = new ContentResult
            {
                Content = serializer.Serialize(res),
                ContentType = "application/json"
            };
            return result;

            //if (_simulation != null)
            //{
            //    var res = _simulation.Select(x => new object[] { x }).ToArray();
            //    return Json(res, JsonRequestBehavior.AllowGet);
            //}
            //return Json(null, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult DownloadResult()
        {
            Response.Clear();
            Response.AddHeader("Content-Disposition", "attachment; filename=dataOut.csv");
            Response.ContentType = "text/csv";

            if (_simulationDataOut != null)
            {
                bool wereLinesWritten = false;
                for (var i = 0; i < _simulationDataOut.Length; i++)
                {

Offwind.WebApp/Offwind.WebApp/Areas/EngineeringTools/Views/WakeSimulation2New/Nowcasting.cshtml
@model Offwind.WebApp.Areas.EngineeringTools.Models.WakeSimulation2New.VNowcastingProperties

@{
    var wasWakeSimulationPerformed = (bool?)(ViewBag.WasWakeSimulationPerformed) ?? false;
}

<ul class="breadcrumb">
    <li><a href="@Url.Action("Index", "Home", new { area = "" })"><i class="icon-home"></i></a> <span class="divider">/</span></li>
    <li><a href="@Url.Action("Index", "EngineeringTools", new { area = "EngineeringTools" })">Engineering Tools</a> <span class="divider">/</span></li>
    <li>Wind Farm Control</li>
</ul>

@section styles
{
    <style type="text/css">
        /*
        .alert-warning {
          color: #996633;
          background-color: #ffffcc;
          border-color: #996633;
        }
        */
    </style>
}

<div class="row-fluid row-content-block">
    <div class="span12 well">
        <div id="alert-error" class="alert alert-error@(wasWakeSimulationPerformed ? " hidden" : string.Empty)">
            Wind Farm Control Simulation has not been performed yet. To run Nowcasting Simulation please run <a href="@Url.Action("Simulation", "WakeSimulation2New", new { area = "EngineeringTools" })">Wind Farm Control Simulation</a> first.
        </div>

        <div class="fancy-tab-container">
            <ul class="nav nav-tabs fancy">
                <li class="active"><a href="#parameters" data-toggle="tab">Parameters</a></li>
                <li class="hidden"><a href="#results" data-toggle="tab">Results</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="parameters">
                    <form class="form-horizontal" method="post">
                        <br />
                        <fieldset>
                            <!--@Html.EditorFor(m => m.Method)-->
                            <div class="control-group">
                                @Html.LabelFor(m => m.Method, new { @class = "control-label" })
                                <div class="controls controls-row">
                                    @Html.EnumDropDownListFor(m => m.Method, new { @class = "input-xlarge" })
                                </div>
                            </div>
                            @Html.EditorFor(m => m.TimeForStarting)
                            @Html.EditorFor(m => m.Decimation)
                            @Html.EditorFor(m => m.SamplingTime)
                        </fieldset>

                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary@(wasWakeSimulationPerformed ? string.Empty : " disabled")"@(wasWakeSimulationPerformed ? string.Empty : "disabled=\"disabled\"")>Run</button>
                        </div>
                    </form>
                </div>
                <div class="tab-pane" id="results">
                    <div class="chart" id="nowcastingChart" style="width: 100px; height: 560px;"></div>
                    <div id="alert-warnings" class="alert alert-warning hidden" style="margin: 20px;">
                        Warnings:
                        <a class="close" data-dismiss="alert">×</a>
                        <div></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    @Scripts.Render("~/static/Highcharts-3.0.4/highcharts.js")

    <script type="text/javascript">
        $(document).ready(function () {
            $('#SamplingTime').attr('readonly', 'readonly').attr('disabled', 'disabled');

            $('#alert-warnings').bind('close', function () {
                $('#alert-warnings').fadeOut();
                return false;
            });

            function formatNumber(value, digitsAfterPointNumber) {
                var powerOfTen = Math.pow(10, digitsAfterPointNumber);
                formattedValueString = String(Math.round(value * powerOfTen) / powerOfTen);
                return formattedValueString;
            }

            $.ajax({
                url: "@Url.Action("GetNowcastingSimulationResults", "WakeSimulation2New", new { area = "EngineeringTools" })",
                dataType: 'json',
                type: 'GET',
                success: function (res) {
                    if (!res) return;
                    var data = res.data;

                    if (data == null) {
                        return;
                    }

                    var warningMessages = res.warningMessages;
                    if (warningMessages != null && warningMessages.length >= 1) {
                        $('#alert-warnings div').empty();
                        $('#alert-warnings div').append('<ul />');
                        for (var i = 0; i < warningMessages.length; i++) {
                            $('#alert-warnings ul').append('<li>' + warningMessages[i] + '</li>')
                        }
                        $('#alert-warnings').removeClass('hidden').hide().fadeIn();
                    }

                    var w = $('.tab-content').width();
                    $('.chart').width(w);
                    show_graph(data);
                    $('[href="#results"]').closest('.nav-tabs li').removeClass('hidden');
                    $('[href="#results"]').click();
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    if (typeof (console) !== 'undefined' && console.debug != null) {
                        console.debug(jqXHR, textStatus, errorThrown);
                    }
                },
                complete: function (jqXHR, textStatus) {
                }
            });
        });
        
        function show_graph(data) {
            var colors = [ '#000000', '#FF0000', '#00FF00', '#0000FF' ];
            var place = "nowcastingChart";
            var method = data.Method;
            var title = "Nowcasting with " + method + " model based on total wind farm power, Offwind simulation";
            var time = data.Time;
            var x = data.X;
            var xhmsAll = data.XhmsAll;
            var xhmsAllTimeOffset = data.XhmsAllTimeOffset;
            var xhmsLLength = data.XhmsLLength;
            var xhmsUOffset = data.XhmsUOffset;
            var series_titles = [ 'WF Power', 'Forecast lower conf. lim.', 'Forecast', 'Forecast upper conf. lim.' ];

            var chart = new Highcharts.Chart({
                chart: {
                    renderTo: place
                },
                title: {
                    text: title
                },
                xAxis: {
                    min: 0,
                    title: {
                        text: 'Time [h]'
                    }
                },
                yAxis: {
                    title: {
                        text: 'Power [MW]'
                    }
                },
                legend: {
                    enabled: true,
                    maxHeight: 80
                }
            });
            chart.showLoading('Loading data...');
            var skip = function(jx) {
                return false;
            };
            if (time.length > 900) {
                var step = Math.ceil(time.length / 1000);
                skip = function(jx) {
                    if (jx == 0) return false;
                    if (jx % step != 0) {
                        return true;
                    }
                    return false;
                };
            }

            {
                var i = 0;
                var func = [];
                for (var j = 0; j < time.length; j++) {
                    if (skip(j)) continue;
                    func.push({
                        x: time[j],
                        y: x[j]
                    });
                }
                var series = chart.addSeries({
                    type: 'line',
                    name: series_titles[i],
                    shadow: false,
                    lineWidth: 1,
                    color: colors[i % colors.length],
                    marker: {
                        enabled: false
                    }
                }, false);
                series.setData(func, false);
            }

            var dashStyles = [ 'Solid', 'Dash', 'Dot' ];
            var xhmsBounds = [ [ 0, xhmsLLength - 1 ], [ xhmsLLength, xhmsUOffset - 1 ], [ xhmsUOffset, xhmsAll.length - 1 ] ];
            for (var segmentIndex = 0; segmentIndex <= 2; segmentIndex++) {
                for (var lineIndex = 0; lineIndex <= 2; lineIndex++) {
                    func = [ ];
                    for (var timePointIndex = xhmsBounds[segmentIndex][0]; timePointIndex <= xhmsBounds[segmentIndex][1]; timePointIndex++) {
                        //if (skip(xhmsAllTimeOffset + timePointIndex)) continue;
                        func.push({
                            x: time[xhmsAllTimeOffset + timePointIndex],
                            y: xhmsAll[timePointIndex][lineIndex]
                        });
                    }
                    var series = chart.addSeries({
                        type: 'line',
                        name: series_titles[1 + lineIndex],
                        showInLegend: (segmentIndex == 0),
                        shadow: false,
                        dash: dashStyles[segmentIndex],
                        lineWidth: 1,
                        color: colors[(1 + lineIndex) % colors.length],
                        marker: {
                            enabled: false
                        }
                    }, false);
                    series.setData(func, false);
                }
            }

            chart.redraw();
            chart.hideLoading();
        }
    </script>
}

Offwind.WebApp/Offwind.WebApp/Areas/EngineeringTools/Views/WakeSimulation2New/Results.cshtml
@model object

@{
    var wasWakeSimulationPerformed = (bool?)(ViewBag.WasWakeSimulationPerformed) ?? false;
}

<ul class="breadcrumb">
    <li><a href="@Url.Action("Index", "Home", new { area = "" })"><i class="icon-home"></i></a> <span class="divider">/</span></li>
    <li><a href="@Url.Action("Index", "EngineeringTools", new { area = "EngineeringTools" })">Engineering Tools</a> <span class="divider">/</span></li>
    <li>Wind Farm Control</li>
</ul>

<div class="row-fluid row-content-block">
    <div class="span12 well">
        <div id="alert-error" class="alert alert-error@(wasWakeSimulationPerformed ? " hidden" : string.Empty)">
            Wind Farm Control Simulation has not been performed yet. To view or download results please run <a href="@Url.Action("Simulation", "WakeSimulation2New", new { area = "EngineeringTools" })">Wind Farm Control Simulation</a> first.
        </div>

        <div class="fancy-tab-container">
            <ul class="nav nav-tabs fancy">
                <li class="active"><a href="#result-1" data-toggle="tab">P<sub>individual</sub></a></li>
                <li><a href="#result-2" data-toggle="tab">Wind Speed</a></li>
                <li><a href="#result-3" data-toggle="tab">P<sub>total</sub></a></li>
                <li><a href="#result-4" data-toggle="tab">Pitch angle</a></li>
                <li><a href="#result-5" data-toggle="tab">Revolutional Velocity</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="result-1">
                    <div class="chart" id="powerReference" style="width: 100px; height: 560px;"></div>
                </div>
                <div class="tab-pane" id="result-2">
                    <div class="chart" id="windSpeed" style="height: 560px;"></div>
                </div>
                <div class="tab-pane" id="result-3">
                    <div class="chart" id="power" style="width: 100%; height: 560px;"></div>
                </div>
                <div class="tab-pane" id="result-4">
                    <div class="chart" id="pitchAngle" style="height: 560px;"></div>
                </div>
                <div class="tab-pane" id="result-5">
                    <div class="chart" id="revolutionalVelocity" style="height: 560px;"></div>
                </div>
            </div>
        </div>

        <div class="form-actions">
            <p>
                To download result as a list of <b><i>Time [s]</i></b>, <b><i>Produced Power [MW]</i></b>, <b><i>Reference Power [MW]</i></b>, <b><i>Available Power [MW]</i></b> values click button below.
            </p>
            <p><a class="btn btn-success btn-large@(wasWakeSimulationPerformed ? string.Empty : " disabled")" id="download-link" href="@Url.Action("DownloadResult", "WakeSimulation2New", new { area = "EngineeringTools" })">Download result</a></p>
        </div>
    </div>
</div>

@section scripts
{
    @Scripts.Render("~/static/Highcharts-3.0.4/highcharts.js")

    <script type="text/javascript">
        $(document).ready(function () {
            $('#download-link').click(function () {
                return !($(this).hasClass('disabled'));
            });

            function formatNumber(value, digitsAfterPointNumber) {
                var powerOfTen = Math.pow(10, digitsAfterPointNumber);
                formattedValueString = String(Math.round(value * powerOfTen) / powerOfTen);
                return formattedValueString;
            }

            $.ajax({
                url: "@Url.Action("GetSimulationResults", "WakeSimulation2New", new { area = "EngineeringTools" })",
                dataType: 'json',
                type: 'GET',
                success: function(res) {
                    if (!res) return;
                    var data = res.data;
                    if (!data || !(data.length >= 1)) {
                        return;
                    }
                    var turbines = res.turbines;
                    var turbines_titles = null;
                    if (turbines != null) {
                        turbines_titles = [];
                        for (var i = 0; i < turbines.length; i++) {
                            turbines_titles.push('Turbine #' + (turbines[i].n + 1) + ' (' + formatNumber(turbines[i].x, 2) + ', ' + formatNumber(turbines[i].y, 2) + ')');
                        }
                    }
                    var w = $('.tab-content').width();
                    $('.chart').width(w);
                    show_graph(data, "powerReference", "Individual Power Reference", "Time [s]", "Power Reference [MW]", 0, 0, turbines_titles);
                    show_graph(data, "windSpeed", "Wind Speed @("@") individual turbine", "Time [s]", "Wind Speed [m/s]", 1, 0, turbines_titles);
                    show_graph(data, "power", "Power Plot", "Time [s]", "Power [MW]", 4, 0, ['Reference', 'Available', 'Produced']);
                    show_graph(data, "pitchAngle", "Evolution of Pitch angle over time", "Time [s]", "Pitch Angle [deg]", 2, 0, turbines_titles);
                    show_graph(data, "revolutionalVelocity", "Evolution of Revolutional Velocity over time", "Time [s]", "Revolutional Velocity [rpm]", 3, 0, turbines_titles);
                }
            });
        });
        
        function show_graph(data, place, title, x_title, y_title, graph_num, adv_graph_data_offset, series_titles) {
            var colors = [ '#0000FF', '#007F00', '#FF0000', '#00BFBF', '#BF00BF', '#BFBF00', '#3F3F3F' ];
            var nturbines = (data[0][0].length - 4) / 4;
            var show_legend = ((series_titles != null) && (series_titles[0] != ""));
            var chart = new Highcharts.Chart({
                chart: {
                    renderTo: place
                },
                title: {
                    text: title
                },
                xAxis: {
                    min: 0,
                    title: {
                        text: x_title
                    }
                },
                yAxis: {
                    title: {
                        text: y_title
                    }
                },
                legend: {
                    enabled: show_legend,
                    maxHeight: 80
                }
            });
            chart.showLoading('Loading data...');
            var shift = graph_num * nturbines + 1 + adv_graph_data_offset;
            if (series_titles != null) {
                nturbines = series_titles.length;
            }
            var skip = function(jx) {
                return false;
            };
            if (data.length > 900) {
                var step = Math.ceil(data.length / 1000);
                skip = function(jx) {
                    if (jx == 0) return false;
                    if (jx % step != 0) {
                        return true;
                    }
                    return false;
                };
            }

            for (var i = 0; i < nturbines; i++) {
                var func = [];
                for (var j = 0; j < data.length; j++) {
                    if (skip(j)) continue;
                    func.push({
                        x: data[j][0][0],
                        y: data[j][0][shift + i]
                    });
                }
                var series = chart.addSeries({
                    type: 'line',
                    name: (show_legend) ? series_titles[i] : '',
                    shadow: false,
                    lineWidth: 1,
                    color: colors[i % colors.length],
                    marker: {
                        enabled: false
                    }
                }, false);
                series.setData(func, false);
            }
            chart.redraw();
            chart.hideLoading();
        }
    </script>
}